In [1]:
#import library
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [2]:
#load the dataset
dataset = pd.read_csv("Social_Network_Ads.csv")
dataset

User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]

In [3]:
#changing categorical value to numerical value
dataset = pd.get_dummies(dataset, drop_first=True)
dataset=dataset.astype(int)
dataset

User ID  Age  EstimatedSalary  Purchased  Gender_Male
0    15624510   19            19000          0            1
1    15810944   35            20000          0            1
2    15668575   26            43000          0            0
3    15603246   27            57000          0            0
4    15804002   19            76000          0            1
..        ...  ...              ...        ...          ...
395  15691863   46            41000          1            0
396  15706071   51            23000          1            1
397  15654296   50            20000          1            0
398  15755018   36            33000          0            1
399  15594041   49            36000          1            0

[400 rows x 5 columns]

In [4]:
# to find the purchased not purchased count
dataset['Purchased'].value_counts()

Purchased
0    257
1    143
Name: count, dtype: int64

In [5]:
dataset.columns

Index(['User ID', 'Age', 'EstimatedSalary', 'Purchased', 'Gender_Male'], dtype='object')

In [6]:
independent = dataset[['User ID', 'Age', 'EstimatedSalary','Gender_Male']]
dependent = dataset[['Purchased']]

In [7]:
independent.shape
dependent.shape

(400, 1)

In [8]:
#split model for training and testing
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test = train_test_split(independent, dependent, test_size=1/3, random_state=0)

In [9]:
#Model Creation
from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier(criterion='entropy',splitter= 'best',random_state = 0)
classifier.fit(X_train,Y_train)

DecisionTreeClassifier(criterion='entropy', random_state=0)

In [10]:
# to test the data
test_Pred = classifier.predict(X_test)
test_Pred

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1,
       0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1,
       0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0,
       0, 1])

In [11]:
#Evalution using confusion matrix
from sklearn.metrics import confusion_matrix
con_mat = confusion_matrix(Y_test,test_Pred)
con_mat

array([[80,  5],
       [13, 36]], dtype=int64)

In [12]:
#Create an report 
from sklearn.metrics import classification_report
class_report = classification_report(Y_test,test_Pred)
print(class_report)

              precision    recall  f1-score   support

           0       0.86      0.94      0.90        85
           1       0.88      0.73      0.80        49

    accuracy                           0.87       134
   macro avg       0.87      0.84      0.85       134
weighted avg       0.87      0.87      0.86       134



In [13]:
id_input=int(input("Enter the UserId: "))
age_input=int(input("Enter the age: "))
Salary= int(input("Enter the salary: "))
Gender = int(input("Enter the gender: "))

Enter the UserId: 1
Enter the age: 30
Enter the salary: 10000
Enter the gender: 1


In [14]:
classifier.predict([[id_input,age_input,Salary,Gender]])

C:\Anaconda3\Lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(


array([0])

In [15]:
classifier.predict([[2,45,78000,1]])

C:\Anaconda3\Lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(


array([1])

# Grid Search CV

In [16]:
#to develope a model
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import GridSearchCV
parameters = {'criterion': ['gini', 'entropy', 'log_loss'],
             'splitter':['best', 'random'],
             'max_features':['sqrt', 'log2']}
grid = GridSearchCV(DecisionTreeClassifier(),parameters,refit=True,verbose=3,n_jobs=-1,scoring='f1_weighted')
grid.fit(X_train,Y_train)

Fitting 5 folds for each of 12 candidates, totalling 60 fits


GridSearchCV(estimator=DecisionTreeClassifier(), n_jobs=-1,
             param_grid={'criterion': ['gini', 'entropy', 'log_loss'],
                         'max_features': ['sqrt', 'log2'],
                         'splitter': ['best', 'random']},
             scoring='f1_weighted', verbose=3)

In [17]:
# to check the best parameter
print(grid.best_params_)

{'criterion': 'entropy', 'max_features': 'log2', 'splitter': 'best'}


In [20]:
#to get the results
classifier = grid.cv_results_
classifier
print("The value of best parameter",format(grid.best_params_))

The value of best parameter {'criterion': 'entropy', 'max_features': 'log2', 'splitter': 'best'}


In [21]:
#to get the result in table
table = pd.DataFrame.from_dict(classifier)
table

mean_fit_time  std_fit_time  mean_score_time  std_score_time  \
0        0.012565      0.000671         0.025190        0.001321   
1        0.015430      0.004003         0.025555        0.003269   
2        0.010257      0.000553         0.022805        0.001037   
3        0.009848      0.000871         0.021318        0.000389   
4        0.005087      0.004426         0.021911        0.007367   
5        0.007686      0.006722         0.023913        0.005044   
6        0.006190      0.003115         0.021188        0.005830   
7        0.012062      0.006095         0.015406        0.000448   
8        0.012501      0.006250         0.021870        0.007653   
9        0.003124      0.006248         0.028118        0.006248   
10       0.009373      0.007653         0.018746        0.006249   
11       0.012369      0.006204         0.017077        0.009565   

   param_criterion param_max_features param_splitter  \
0             gini               sqrt           best   
1             gini               sqrt         random   
2             gini               log2           best   
3             gini               log2         random   
4          entropy               sqrt           best   
5          entropy               sqrt         random   
6          entropy               log2           best   
7          entropy               log2         random   
8         log_loss               sqrt           best   
9         log_loss               sqrt         random   
10        log_loss               log2           best   
11        log_loss               log2         random   

                                               params  split0_test_score  \
0   {'criterion': 'gini', 'max_features': 'sqrt', ...           0.829615   
1   {'criterion': 'gini', 'max_features': 'sqrt', ...           0.645871   
2   {'criterion': 'gini', 'max_features': 'log2', ...           0.887346   
3   {'criterion': 'gini', 'max_features': 'log2', ...           0.749046   
4   {'criterion': 'entropy', 'max_features': 'sqrt...           0.847141   
5   {'criterion': 'entropy', 'max_features': 'sqrt...           0.710438   
6   {'criterion': 'entropy', 'max_features': 'log2...           0.869532   
7   {'criterion': 'entropy', 'max_features': 'log2...           0.822092   
8   {'criterion': 'log_loss', 'max_features': 'sqr...           0.826263   
9   {'criterion': 'log_loss', 'max_features': 'sqr...           0.770712   
10  {'criterion': 'log_loss', 'max_features': 'log...           0.804764   
11  {'criterion': 'log_loss', 'max_features': 'log...           0.765716   

    split1_test_score  split2_test_score  split3_test_score  \
0            0.834012           0.833323           0.888646   
1            0.813511           0.833653           0.808775   
2            0.831253           0.852044           0.844370   
3            0.790949           0.778179           0.783837   
4            0.793754           0.796284           0.808775   
5            0.795789           0.850543           0.849057   
6            0.813511           0.851527           0.886792   
7            0.831253           0.720804           0.773585   
8            0.868752           0.796687           0.886792   
9            0.793754           0.720804           0.808775   
10           0.870047           0.778067           0.868632   
11           0.825959           0.808775           0.791152   

    split4_test_score  mean_test_score  std_test_score  rank_test_score  
0            0.826499         0.842419        0.023271                4  
1            0.808775         0.782117        0.068740               12  
2            0.831098         0.849222        0.020670                2  
3            0.808775         0.782157        0.019498               11  
4            0.905069         0.830205        0.042024                5  
5            0.829124         0.806990        0.052162                8  
6            0.826499         0.849572        0.026908         

In [22]:
# to check in test data
grid_pred= grid.predict(X_test)
grid_pred

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0,
       0, 1])

In [24]:
#confusion matrix
from sklearn.metrics import confusion_matrix
con_mat=confusion_matrix(Y_test,grid_pred)
con_mat

array([[78,  7],
       [12, 37]], dtype=int64)

In [26]:
#classification report
from sklearn.metrics import classification_report
class_report=classification_report(Y_test,grid_pred)
print(class_report)

              precision    recall  f1-score   support

           0       0.87      0.92      0.89        85
           1       0.84      0.76      0.80        49

    accuracy                           0.86       134
   macro avg       0.85      0.84      0.84       134
weighted avg       0.86      0.86      0.86       134



In [28]:
#f1score
from sklearn.metrics import f1_score
f1_macro=f1_score(Y_test,grid_pred,average='weighted')
print("The f1_macro value for best parameter {}:".format(grid.best_params_),f1_macro)

The f1_macro value for best parameter {'criterion': 'entropy', 'max_features': 'log2', 'splitter': 'best'}: 0.8564229543526606


In [29]:
#roc_auc
from sklearn.metrics import roc_auc_score
roc = roc_auc_score(Y_test,grid.predict_proba(X_test)[:,1])
roc

0.8363745498199279

In [30]:
#to check the user input value 
Future_pred = grid.predict([[1,23,20000,0]])
print("Future Prediction ={}".format(Future_pred))

Future Prediction =[0]


C:\Anaconda3\Lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(
