In [1]:
#import library
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [2]:
#load the dataset
dataset = pd.read_csv("Social_Network_Ads.csv")
dataset

User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]

In [3]:
#changing categorical value to numerical value
dataset = pd.get_dummies(dataset, drop_first=True)
dataset=dataset.astype(int)
dataset

User ID  Age  EstimatedSalary  Purchased  Gender_Male
0    15624510   19            19000          0            1
1    15810944   35            20000          0            1
2    15668575   26            43000          0            0
3    15603246   27            57000          0            0
4    15804002   19            76000          0            1
..        ...  ...              ...        ...          ...
395  15691863   46            41000          1            0
396  15706071   51            23000          1            1
397  15654296   50            20000          1            0
398  15755018   36            33000          0            1
399  15594041   49            36000          1            0

[400 rows x 5 columns]

In [4]:
# to find the purchased not purchased count
dataset['Purchased'].value_counts()

Purchased
0    257
1    143
Name: count, dtype: int64

In [5]:
dataset.columns

Index(['User ID', 'Age', 'EstimatedSalary', 'Purchased', 'Gender_Male'], dtype='object')

In [6]:
independent = dataset[['User ID', 'Age', 'EstimatedSalary','Gender_Male']]
dependent = dataset[['Purchased']]

In [7]:
independent.shape
dependent.shape

(400, 1)

In [8]:
#split model for training and testing
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test = train_test_split(independent, dependent, test_size=1/3, random_state=0)

In [9]:
#Model Creation
from sklearn.svm import SVC
classifier = SVC(C=10,kernel= 'rbf',random_state = 0)
classifier.fit(X_train,Y_train)

C:\Anaconda3\Lib\site-packages\sklearn\utils\validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVC(C=10, random_state=0)

In [10]:
# to test the data
test_Pred = classifier.predict(X_test)
test_Pred

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0])

In [11]:
#Evalution using confusion matrix
from sklearn.metrics import confusion_matrix
con_mat = confusion_matrix(Y_test,test_Pred)
con_mat

array([[85,  0],
       [49,  0]], dtype=int64)

In [12]:
#Create an report 
from sklearn.metrics import classification_report
class_report = classification_report(Y_test,test_Pred)
print(class_report)

              precision    recall  f1-score   support

           0       0.63      1.00      0.78        85
           1       0.00      0.00      0.00        49

    accuracy                           0.63       134
   macro avg       0.32      0.50      0.39       134
weighted avg       0.40      0.63      0.49       134



C:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [13]:
id_input=int(input("Enter the UserId: "))
age_input=int(input("Enter the age: "))
Salary= int(input("Enter the salary: "))
Gender = int(input("Enter the gender: "))

Enter the UserId: 45
Enter the age: 45
Enter the salary: 700000
Enter the gender: 0


In [14]:
classifier.predict([[id_input,age_input,Salary,Gender]])

C:\Anaconda3\Lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but SVC was fitted with feature names
  warnings.warn(


array([0])

In [15]:
classifier.predict([[2,45,78000,1]])

C:\Anaconda3\Lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but SVC was fitted with feature names
  warnings.warn(


array([0])

# Grid Search CV

In [16]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train= sc.fit_transform(X_train)
X_test= sc.transform(X_test)

In [18]:
#to develope a model
from sklearn.svm import SVC
from sklearn.model_selection import GridSearchCV
parameters = {'C': [10,50,100],
             'kernel':['linear', 'poly', 'rbf', 'sigmoid'],
             'gamma':['scale', 'auto']}
grid = GridSearchCV(SVC(),parameters,refit=True,verbose=3,n_jobs=-1,scoring='f1_weighted')
grid.fit(X_train,Y_train)

Fitting 5 folds for each of 24 candidates, totalling 120 fits


C:\Anaconda3\Lib\site-packages\sklearn\utils\validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


GridSearchCV(estimator=SVC(), n_jobs=-1,
             param_grid={'C': [10, 50, 100], 'gamma': ['scale', 'auto'],
                         'kernel': ['linear', 'poly', 'rbf', 'sigmoid']},
             scoring='f1_weighted', verbose=3)

In [19]:
print(grid.best_params_)

{'C': 10, 'gamma': 'scale', 'kernel': 'rbf'}


In [22]:
classifier = grid.cv_results_
# print(classifier)
print("The value for best parameter: ",format(grid.best_params_))

The value for best parameter:  {'C': 10, 'gamma': 'scale', 'kernel': 'rbf'}


In [23]:
table=pd.DataFrame.from_dict(classifier)
table

mean_fit_time  std_fit_time  mean_score_time  std_score_time param_C  \
0        0.020189  8.173942e-03         0.020269    4.597817e-03      10   
1        0.022161  7.808542e-03         0.015626    3.894332e-06      10   
2        0.006250  7.654773e-03         0.019129    6.299269e-03      10   
3        0.016186  1.015566e-03         0.015254    8.775877e-04      10   
4        0.015623  3.200142e-06         0.028119    6.248331e-03      10   
5        0.015621  7.629395e-07         0.015621    7.629395e-07      10   
6        0.009373  7.652865e-03         0.021869    7.652942e-03      10   
7        0.009373  7.652942e-03         0.018746    6.248760e-03      10   
8        0.028117  6.248546e-03         0.025439    8.681647e-03      50   
9        0.022703  8.687277e-03         0.019094    7.592010e-03      50   
10       0.012806  2.939943e-03         0.015671    6.097638e-03      50   
11       0.010685  7.335629e-03         0.017550    7.045564e-03      50   
12       0.030067  1.134295e-02         0.017001    7.279609e-03      50   
13       0.035103  1.532433e-02         0.018257    6.785669e-03      50   
14       0.016676  2.540184e-03         0.015510    3.129587e-03      50   
15       0.014903  1.445907e-03         0.015621    6.705287e-06      50   
16       0.049986  6.246305e-03         0.015621    7.921814e-07     100   
17       0.049988  1.821754e-02         0.018975    6.150244e-03     100   
18       0.015400  4.468054e-04         0.012497    6.248617e-03     100   
19       0.012497  6.248260e-03         0.015621    8.064048e-07     100   
20       0.044652  1.082182e-02         0.009604    7.852585e-03     100   
21       0.034179  1.224125e-02         0.007214    6.509751e-03     100   
22       0.011906  6.216193e-03         0.009151    7.483143e-03     100   
23       0.009150  7.481699e-03         0.016164    6.743336e-04     100   

   param_gamma param_kernel  \
0        scale       linear   
1        scale         poly   
2        scale          rbf   
3        scale      sigmoid   
4         auto       linear   
5         auto         poly   
6         auto          rbf   
7         auto      sigmoid   
8        scale       linear   
9        scale         poly   
10       scale          rbf   
11       scale      sigmoid   
12        auto       linear   
13        auto         poly   
14        auto          rbf   
15        auto      sigmoid   
16       scale       linear   
17       scale         poly   
18       scale          rbf   
19       scale      sigmoid   
20        auto       linear   
21        auto         poly   
22        auto          rbf   
23        auto      sigmoid   

                                               params  split0_test_score  \
0     {'C': 10, 'gamma': 'scale', 'kernel': 'linear'}           0.822092   
1       {'C': 10, 'gamma': 'scale', 'kernel': 'poly'}           0.799620   
2        {'C': 10, 'gamma': 'scale', 'kernel': 'rbf'}           0.887346   
3    {'C': 10, 'gamma': 'scale', 'kernel': 'sigmoid'}           0.749046   
4      {'C': 10, 'gamma': 'auto', 'kernel': 'linear'}           0.822092   
5        {'C': 10, 'gamma': 'auto', 'kernel': 'poly'}           0.799620   
6         {'C': 10, 'gamma': 'auto', 'kernel': 'rbf'}           0.887346   
7     {'C': 10, 'gamma': 'auto', 'kernel': 'sigmoid'}           0.749046   
8     {'C': 50, 'gamma': 'scale', 'kernel': 'linear'}           0.822092   
9       {'C': 50, 'gamma': 'scale', 'kernel': 'poly'}           0.804764   
10       {'C': 50, 'gamma': 'scale', 'kernel': 'rbf'}           0.847141   
11   {'C': 50, 'gamma': 'scale', 'kernel': 'sigmoid'}           0.753889   
12     {'C': 50, 'gamma': 'auto', 'kernel': 'linear'}           0.822092   
13       {'C': 50, 'gamma': 'auto', 'kernel': 'poly'}           0.804764   
14        {'C': 50, 'gamma': 'auto', 'kernel': 'rbf'}           0.847141   
15    {'C': 50, 'gamma': 'auto', 'kernel': 'sigmoid'}           0.732497   
16   {'C': 100, 'gamma': 'scale', '

In [26]:
grid_pred=grid.predict(X_test)
grid_pred

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1,
       1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1,
       0, 1])

In [27]:
from sklearn.metrics import confusion_matrix
con_mat=confusion_matrix(Y_test,grid_pred)
con_mat

array([[79,  6],
       [ 6, 43]], dtype=int64)

In [30]:
from sklearn.metrics import classification_report
class_report = classification_report(Y_test,grid_pred)
print(class_report)

              precision    recall  f1-score   support

           0       0.93      0.93      0.93        85
           1       0.88      0.88      0.88        49

    accuracy                           0.91       134
   macro avg       0.90      0.90      0.90       134
weighted avg       0.91      0.91      0.91       134



In [32]:
from sklearn.metrics import roc_auc_score
roc = roc_auc_score(Y_test,grid_pred)
roc

0.9034813925570228

In [33]:
#to check the user input value 
Future_pred = grid.predict([[1,23,20000,0]])
print("Future Prediction ={}".format(Future_pred))

Future Prediction =[1]
