In [1]:
#import library
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [2]:
#load the dataset
dataset = pd.read_csv("Social_Network_Ads.csv")
dataset

User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]

In [3]:
#changing categorical value to numerical value
dataset = pd.get_dummies(dataset, drop_first=True)
dataset=dataset.astype(int)
dataset

User ID  Age  EstimatedSalary  Purchased  Gender_Male
0    15624510   19            19000          0            1
1    15810944   35            20000          0            1
2    15668575   26            43000          0            0
3    15603246   27            57000          0            0
4    15804002   19            76000          0            1
..        ...  ...              ...        ...          ...
395  15691863   46            41000          1            0
396  15706071   51            23000          1            1
397  15654296   50            20000          1            0
398  15755018   36            33000          0            1
399  15594041   49            36000          1            0

[400 rows x 5 columns]

In [4]:
dataset = dataset.drop(['User ID'],axis=1) # axis 1 will remove the column 1 and axis 0 will remove the row 

In [5]:
# to find the purchased not purchased count
dataset['Purchased'].value_counts()

Purchased
0    257
1    143
Name: count, dtype: int64

In [6]:
dataset.columns

Index(['Age', 'EstimatedSalary', 'Purchased', 'Gender_Male'], dtype='object')

In [7]:
independent = dataset[['Age', 'EstimatedSalary','Gender_Male']]
dependent = dataset[['Purchased']]

In [8]:
independent.shape
dependent.shape

(400, 1)

In [9]:
#split model for training and testing
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test = train_test_split(independent, dependent, test_size=1/3, random_state=0)

In [10]:
#Model Creation
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(C=10,random_state = 0)
classifier.fit(X_train,Y_train)

C:\Anaconda3\Lib\site-packages\sklearn\utils\validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LogisticRegression(C=10, random_state=0)

In [11]:
# to test the data
test_Pred = classifier.predict(X_test)
test_Pred

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0])

In [12]:
#Evalution using confusion matrix
from sklearn.metrics import confusion_matrix
con_mat = confusion_matrix(Y_test,test_Pred)
con_mat

array([[85,  0],
       [49,  0]], dtype=int64)

In [13]:
#Create an report 
from sklearn.metrics import classification_report
class_report = classification_report(Y_test,test_Pred)
print(class_report)

              precision    recall  f1-score   support

           0       0.63      1.00      0.78        85
           1       0.00      0.00      0.00        49

    accuracy                           0.63       134
   macro avg       0.32      0.50      0.39       134
weighted avg       0.40      0.63      0.49       134



C:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [14]:
# id_input=int(input("Enter the UserId: "))
age_input=int(input("Enter the age: "))
Salary= int(input("Enter the salary: "))
Gender = int(input("Enter the gender: "))

Enter the age: 1
Enter the salary: 500000
Enter the gender: 0


In [15]:
classifier.predict([[age_input,Salary,Gender]])

C:\Anaconda3\Lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(


array([0])

In [16]:
classifier.predict([[45,78000,1]])

C:\Anaconda3\Lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(


array([0])

# Grid Search CV

In [20]:
#to develope a model
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import GridSearchCV
parameters = {'C': [10,50,100],
             'penalty':['l1','l2','elasticnet'],
             'solver':['lbfgs', 'liblinear', 'newton-cg', 'newton-cholesky', 'sag', 'saga'],
             'multi_class':['auto', 'ovr', 'multinomial']}
grid = GridSearchCV(LogisticRegression(),parameters,refit=True,verbose=3,n_jobs=-1,scoring='f1_weighted')
grid.fit(X_train,Y_train)

Fitting 5 folds for each of 162 candidates, totalling 810 fits


C:\Anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:378: FitFailedWarning: 
495 fits failed out of a total of 810.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
45 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 686, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py", line 1162, in fit
    solver = _check_solver(self.solver, self.penalty, self.dual)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py", line 54, in _check_solver
    rais

GridSearchCV(estimator=LogisticRegression(), n_jobs=-1,
             param_grid={'C': [10, 50, 100],
                         'multi_class': ['auto', 'ovr', 'multinomial'],
                         'penalty': ['l1', 'l2', 'elasticnet'],
                         'solver': ['lbfgs', 'liblinear', 'newton-cg',
                                    'newton-cholesky', 'sag', 'saga']},
             scoring='f1_weighted', verbose=3)

In [21]:
print(grid.best_params_)

{'C': 10, 'multi_class': 'auto', 'penalty': 'l1', 'solver': 'liblinear'}


In [30]:
classifier = grid.cv_results_
# print(classifier)
print("The value for best parameter: ",format(grid.best_params_))

The value for best parameter:  {'C': 10, 'multi_class': 'auto', 'penalty': 'l1', 'solver': 'liblinear'}


In [31]:
table=pd.DataFrame.from_dict(classifier)
table

mean_fit_time  std_fit_time  mean_score_time  std_score_time param_C  \
0         0.004347      0.005801         0.000000        0.000000      10   
1         0.015630      0.003559         0.028849        0.003347      10   
2         0.003124      0.006249         0.000000        0.000000      10   
3         0.001539      0.003078         0.000000        0.000000      10   
4         0.001503      0.003005         0.000000        0.000000      10   
..             ...           ...              ...             ...     ...   
157       0.003124      0.006248         0.000000        0.000000     100   
158       0.004380      0.006380         0.000000        0.000000     100   
159       0.000000      0.000000         0.000000        0.000000     100   
160       0.000000      0.000000         0.000000        0.000000     100   
161       0.012559      0.003328         0.000000        0.000000     100   

    param_multi_class param_penalty     param_solver  \
0                auto            l1            lbfgs   
1                auto            l1        liblinear   
2                auto            l1        newton-cg   
3                auto            l1  newton-cholesky   
4                auto            l1              sag   
..                ...           ...              ...   
157       multinomial    elasticnet        liblinear   
158       multinomial    elasticnet        newton-cg   
159       multinomial    elasticnet  newton-cholesky   
160       multinomial    elasticnet              sag   
161       multinomial    elasticnet             saga   

                                                params  split0_test_score  \
0    {'C': 10, 'multi_class': 'auto', 'penalty': 'l...                NaN   
1    {'C': 10, 'multi_class': 'auto', 'penalty': 'l...           0.804764   
2    {'C': 10, 'multi_class': 'auto', 'penalty': 'l...                NaN   
3    {'C': 10, 'multi_class': 'auto', 'penalty': 'l...                NaN   
4    {'C': 10, 'multi_class': 'auto', 'penalty': 'l...                NaN   
..                                                 ...                ...   
157  {'C': 100, 'multi_class': 'multinomial', 'pena...                NaN   
158  {'C': 100, 'multi_class': 'multinomial', 'pena...                NaN   
159  {'C': 100, 'multi_class': 'multinomial', 'pena...                NaN   
160  {'C': 100, 'multi_class': 'multinomial', 'pena...                NaN   
161  {'C': 100, 'multi_class': 'multinomial', 'pena...                NaN   

     split1_test_score  split2_test_score  split3_test_score  \
0                  NaN                NaN                NaN   
1             0.811321            0.68205            0.92351   
2                  NaN                NaN                NaN   
3                  NaN                NaN                NaN   
4                  NaN                NaN                NaN   
..                 ...                ...                ...   
157                NaN                NaN                NaN   
158                NaN                NaN                NaN   
159                NaN                NaN                NaN   
160                NaN                NaN                NaN   
161                NaN                NaN                NaN   

     split4_test_score  mean_test_score  std_test_score  rank_test_score  
0                  NaN              NaN             NaN               64  
1             0.922185         0.828766        0.089565                1  
2                  NaN              NaN             NaN               64  
3                  NaN              NaN             NaN               64  
4                  NaN              NaN             NaN               64  
..                 ...              ...             ...              ...  
157                NaN              NaN             NaN               64  
158                NaN              NaN             NaN               64  
159                NaN              Na

In [32]:
grid_pred=grid.predict(X_test)
grid_pred

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1,
       0, 1])

In [33]:
from sklearn.metrics import confusion_matrix
con_mat=confusion_matrix(Y_test,grid_pred)
con_mat

array([[79,  6],
       [10, 39]], dtype=int64)

In [34]:
from sklearn.metrics import classification_report
class_report = classification_report(Y_test,grid_pred)
print(class_report)

              precision    recall  f1-score   support

           0       0.89      0.93      0.91        85
           1       0.87      0.80      0.83        49

    accuracy                           0.88       134
   macro avg       0.88      0.86      0.87       134
weighted avg       0.88      0.88      0.88       134



In [35]:
from sklearn.metrics import roc_auc_score
roc = roc_auc_score(Y_test,grid_pred)
roc

0.8626650660264106

In [37]:
#to check the user input value 
Future_pred = grid.predict([[23,20000,0]])
print("Future Prediction ={}".format(Future_pred))

Future Prediction =[0]


C:\Anaconda3\Lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(
