In [1]:
#import library
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [2]:
#load the dataset
dataset = pd.read_csv("Social_Network_Ads.csv")
dataset

User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]

In [3]:
#changing categorical value to numerical value
dataset = pd.get_dummies(dataset, drop_first=True)
dataset=dataset.astype(int)
dataset

User ID  Age  EstimatedSalary  Purchased  Gender_Male
0    15624510   19            19000          0            1
1    15810944   35            20000          0            1
2    15668575   26            43000          0            0
3    15603246   27            57000          0            0
4    15804002   19            76000          0            1
..        ...  ...              ...        ...          ...
395  15691863   46            41000          1            0
396  15706071   51            23000          1            1
397  15654296   50            20000          1            0
398  15755018   36            33000          0            1
399  15594041   49            36000          1            0

[400 rows x 5 columns]

In [4]:
dataset = dataset.drop(['User ID'],axis=1) # axis 1 will remove the column 1 and axis 0 will remove the row 

In [5]:
# to find the purchased not purchased count
dataset['Purchased'].value_counts()

Purchased
0    257
1    143
Name: count, dtype: int64

In [6]:
independent = dataset[['Age', 'EstimatedSalary','Gender_Male']]
dependent = dataset[['Purchased']]

In [7]:
#split model for training and testing
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test = train_test_split(independent, dependent, test_size=1/3, random_state=0)

In [8]:
#Model Creation
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB() 
classifier.fit(X_train,Y_train)
# to test the data
test_Pred = classifier.predict(X_test)
test_Pred
#Evalution using confusion matrix
from sklearn.metrics import confusion_matrix
con_mat = confusion_matrix(Y_test,test_Pred) # error 1 should be lesser than error 2 (i.e) good model
print(con_mat)
#Create an report 
from sklearn.metrics import classification_report
class_report = classification_report(Y_test,test_Pred)
print(class_report)


[[80  5]
 [ 8 41]]
              precision    recall  f1-score   support

           0       0.91      0.94      0.92        85
           1       0.89      0.84      0.86        49

    accuracy                           0.90       134
   macro avg       0.90      0.89      0.89       134
weighted avg       0.90      0.90      0.90       134



C:\Anaconda3\Lib\site-packages\sklearn\utils\validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


# Grid Search CV 

In [14]:
from sklearn.naive_bayes import GaussianNB
from sklearn.model_selection import GridSearchCV
parameters = {}
grid = GridSearchCV(GaussianNB(),parameters,refit=True,verbose=3,n_jobs=-1,scoring='f1_weighted')
grid.fit(X_train,Y_train)
classifier = grid.cv_results_
# print(classifier)
# print("The value for best parameter: ",format(grid.best_params_))
table=pd.DataFrame.from_dict(classifier)
table

Fitting 5 folds for each of 1 candidates, totalling 5 fits


C:\Anaconda3\Lib\site-packages\sklearn\utils\validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


mean_fit_time  std_fit_time  mean_score_time  std_score_time params  \
0       0.013745      0.003646         0.017869        0.003536     {}   

   split0_test_score  split1_test_score  split2_test_score  split3_test_score  \
0           0.822092           0.868752           0.813179           0.962264   

   split4_test_score  mean_test_score  std_test_score  rank_test_score  
0           0.961755         0.885608        0.065175                1

In [16]:
grid_pred=grid.predict(X_test)
grid_pred
from sklearn.metrics import confusion_matrix
con_mat=confusion_matrix(Y_test,grid_pred)
con_mat
from sklearn.metrics import classification_report
class_report = classification_report(Y_test,grid_pred)
print(class_report)

              precision    recall  f1-score   support

           0       0.91      0.94      0.92        85
           1       0.89      0.84      0.86        49

    accuracy                           0.90       134
   macro avg       0.90      0.89      0.89       134
weighted avg       0.90      0.90      0.90       134



In [9]:
#Model Creation
from sklearn.naive_bayes import ComplementNB
classifier = ComplementNB() 
classifier.fit(X_train,Y_train)
# to test the data
test_Pred = classifier.predict(X_test)
test_Pred
#Evalution using confusion matrix
from sklearn.metrics import confusion_matrix
con_mat = confusion_matrix(Y_test,test_Pred) # error 1 should be lesser than error 2 (i.e) good model
print(con_mat)
#Create an report 
from sklearn.metrics import classification_report
class_report = classification_report(Y_test,test_Pred)
print(class_report)


[[40 45]
 [20 29]]
              precision    recall  f1-score   support

           0       0.67      0.47      0.55        85
           1       0.39      0.59      0.47        49

    accuracy                           0.51       134
   macro avg       0.53      0.53      0.51       134
weighted avg       0.57      0.51      0.52       134



C:\Anaconda3\Lib\site-packages\sklearn\utils\validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


# Grid Search CV  

In [18]:
from sklearn.naive_bayes import ComplementNB
from sklearn.model_selection import GridSearchCV
parameters = {}
grid = GridSearchCV(ComplementNB(),parameters,refit=True,verbose=3,n_jobs=-1,scoring='f1_weighted')
grid.fit(X_train,Y_train)
classifier = grid.cv_results_
# print(classifier)
# print("The value for best parameter: ",format(grid.best_params_))
table=pd.DataFrame.from_dict(classifier)
table
grid_pred=grid.predict(X_test)
grid_pred
from sklearn.metrics import confusion_matrix
con_mat=confusion_matrix(Y_test,grid_pred)
con_mat
from sklearn.metrics import classification_report
class_report = classification_report(Y_test,grid_pred)
print(class_report)

Fitting 5 folds for each of 1 candidates, totalling 5 fits
              precision    recall  f1-score   support

           0       0.67      0.47      0.55        85
           1       0.39      0.59      0.47        49

    accuracy                           0.51       134
   macro avg       0.53      0.53      0.51       134
weighted avg       0.57      0.51      0.52       134



C:\Anaconda3\Lib\site-packages\sklearn\utils\validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [10]:
#Model Creation
from sklearn.naive_bayes import MultinomialNB
classifier = MultinomialNB() 
classifier.fit(X_train,Y_train)
# to test the data
test_Pred = classifier.predict(X_test)
test_Pred
#Evalution using confusion matrix
from sklearn.metrics import confusion_matrix
con_mat = confusion_matrix(Y_test,test_Pred) # error 1 should be lesser than error 2 (i.e) good model
print(con_mat)
#Create an report 
from sklearn.metrics import classification_report
class_report = classification_report(Y_test,test_Pred)
print(class_report)

[[85  0]
 [49  0]]
              precision    recall  f1-score   support

           0       0.63      1.00      0.78        85
           1       0.00      0.00      0.00        49

    accuracy                           0.63       134
   macro avg       0.32      0.50      0.39       134
weighted avg       0.40      0.63      0.49       134



C:\Anaconda3\Lib\site-packages\sklearn\utils\validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and be

# Grid Search CV 

In [19]:
from sklearn.naive_bayes import MultinomialNB
from sklearn.model_selection import GridSearchCV
parameters = {}
grid = GridSearchCV(MultinomialNB(),parameters,refit=True,verbose=3,n_jobs=-1,scoring='f1_weighted')
grid.fit(X_train,Y_train)
classifier = grid.cv_results_
# print(classifier)
# print("The value for best parameter: ",format(grid.best_params_))
table=pd.DataFrame.from_dict(classifier)
table
grid_pred=grid.predict(X_test)
grid_pred
from sklearn.metrics import confusion_matrix
con_mat=confusion_matrix(Y_test,grid_pred)
con_mat
from sklearn.metrics import classification_report
class_report = classification_report(Y_test,grid_pred)
print(class_report)

Fitting 5 folds for each of 1 candidates, totalling 5 fits
              precision    recall  f1-score   support

           0       0.63      1.00      0.78        85
           1       0.00      0.00      0.00        49

    accuracy                           0.63       134
   macro avg       0.32      0.50      0.39       134
weighted avg       0.40      0.63      0.49       134



C:\Anaconda3\Lib\site-packages\sklearn\utils\validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and be

In [11]:
#Model Creation
from sklearn.naive_bayes import BernoulliNB
classifier = BernoulliNB() 
classifier.fit(X_train,Y_train)
# to test the data
test_Pred = classifier.predict(X_test)
test_Pred
#Evalution using confusion matrix
from sklearn.metrics import confusion_matrix
con_mat = confusion_matrix(Y_test,test_Pred) # error 1 should be lesser than error 2 (i.e) good model
print(con_mat)
#Create an report 
from sklearn.metrics import classification_report
class_report = classification_report(Y_test,test_Pred)
print(class_report)

[[85  0]
 [49  0]]
              precision    recall  f1-score   support

           0       0.63      1.00      0.78        85
           1       0.00      0.00      0.00        49

    accuracy                           0.63       134
   macro avg       0.32      0.50      0.39       134
weighted avg       0.40      0.63      0.49       134



C:\Anaconda3\Lib\site-packages\sklearn\utils\validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and be

# Grid Search CV 

In [20]:
from sklearn.naive_bayes import BernoulliNB
from sklearn.model_selection import GridSearchCV
parameters = {}
grid = GridSearchCV(BernoulliNB(),parameters,refit=True,verbose=3,n_jobs=-1,scoring='f1_weighted')
grid.fit(X_train,Y_train)
classifier = grid.cv_results_
# print(classifier)
# print("The value for best parameter: ",format(grid.best_params_))
table=pd.DataFrame.from_dict(classifier)
table
grid_pred=grid.predict(X_test)
grid_pred
from sklearn.metrics import confusion_matrix
con_mat=confusion_matrix(Y_test,grid_pred)
con_mat
from sklearn.metrics import classification_report
class_report = classification_report(Y_test,grid_pred)
print(class_report)

Fitting 5 folds for each of 1 candidates, totalling 5 fits
              precision    recall  f1-score   support

           0       0.63      1.00      0.78        85
           1       0.00      0.00      0.00        49

    accuracy                           0.63       134
   macro avg       0.32      0.50      0.39       134
weighted avg       0.40      0.63      0.49       134



C:\Anaconda3\Lib\site-packages\sklearn\utils\validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and be

In [12]:
#Model Creation
from sklearn.naive_bayes import CategoricalNB
classifier = CategoricalNB() 
classifier.fit(X_train,Y_train)
# to test the data
test_Pred = classifier.predict(X_test)
test_Pred
#Evalution using confusion matrix
from sklearn.metrics import confusion_matrix
con_mat = confusion_matrix(Y_test,test_Pred) # error 1 should be lesser than error 2 (i.e) good model
print(con_mat)
#Create an report 
from sklearn.metrics import classification_report
class_report = classification_report(Y_test,test_Pred)
print(class_report)

C:\Anaconda3\Lib\site-packages\sklearn\utils\validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


[[82  3]
 [18 31]]
              precision    recall  f1-score   support

           0       0.82      0.96      0.89        85
           1       0.91      0.63      0.75        49

    accuracy                           0.84       134
   macro avg       0.87      0.80      0.82       134
weighted avg       0.85      0.84      0.84       134



# Grid Search CV 

In [21]:
from sklearn.naive_bayes import CategoricalNB
from sklearn.model_selection import GridSearchCV
parameters = {}
grid = GridSearchCV(CategoricalNB(),parameters,refit=True,verbose=3,n_jobs=-1,scoring='f1_weighted')
grid.fit(X_train,Y_train)
classifier = grid.cv_results_
# print(classifier)
# print("The value for best parameter: ",format(grid.best_params_))
table=pd.DataFrame.from_dict(classifier)
table
grid_pred=grid.predict(X_test)
grid_pred
from sklearn.metrics import confusion_matrix
con_mat=confusion_matrix(Y_test,grid_pred)
con_mat
from sklearn.metrics import classification_report
class_report = classification_report(Y_test,grid_pred)
print(class_report)

Fitting 5 folds for each of 1 candidates, totalling 5 fits
              precision    recall  f1-score   support

           0       0.82      0.96      0.89        85
           1       0.91      0.63      0.75        49

    accuracy                           0.84       134
   macro avg       0.87      0.80      0.82       134
weighted avg       0.85      0.84      0.84       134



C:\Anaconda3\Lib\site-packages\sklearn\model_selection\_search.py:952: UserWarning: One or more of the test scores are non-finite: [nan]
  warnings.warn(
C:\Anaconda3\Lib\site-packages\sklearn\utils\validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
